import { Tool, Category, ToolCategory } from "@/types/tools";

export const CATEGORIES: Record<ToolCategory, Category> = {
  conversion: {
    id: "conversion",
    name: "Data Conversion & Encoding",
    description: "Convert and encode data between different formats",
    icon: "🔄",
    color: "blue",
  },
  files: {
    id: "files",
    name: "File & Image Processing",
    description: "Process, convert, and resize files and images",
    icon: "🎨",
    color: "purple",
  },
  code: {
    id: "code",
    name: "Code & API Tools",
    description: "Tools for developers and code analysis",
    icon: "💻",
    color: "green",
  },
  "dev-utils": {
    id: "dev-utils",
    name: "Development Utilities",
    description: "Handy utilities for development workflows",
    icon: "⚙️",
    color: "amber",
  },
  generators: {
    id: "generators",
    name: "Generators & Config",
    description: "Generate configuration files and utilities",
    icon: "🔧",
    color: "red",
  },
  advanced: {
    id: "advanced",
    name: "Advanced Tools",
    description: "Advanced and specialized tools",
    icon: "🚀",
    color: "pink",
  },
};

export const TOOLS: Tool[] = [
  // Conversion & Encoding
  {
    id: "csv-json",
    name: "CSV ↔ JSON",
    description: "Convert between CSV and JSON formats easily",
    category: "conversion",
    icon: "📊",
    href: "/tools/conversion/csv-json",
    tags: ["csv", "json", "convert", "data"],
    featured: false,
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode/decode text to base64 & view as PNG",
    category: "conversion",
    icon: "🔐",
    href: "/tools/conversion/base64",
    tags: ["base64", "encode", "decode", "image"],
    featured: false,
  },
  {
    id: "markdown-html-pdf",
    name: "Markdown ↔ HTML ↔ PDF",
    description: "Convert between Markdown, HTML, and PDF documents",
    category: "conversion",
    icon: "📄",
    href: "/tools/conversion/markdown-html-pdf",
    tags: ["markdown", "html", "pdf", "document"],
    featured: false,
  },
  {
    id: "base-converter",
    name: "Base Converter",
    description: "Convert between binary, octal, decimal, and hexadecimal",
    category: "conversion",
    icon: "🔢",
    href: "/tools/conversion/base-converter",
    tags: ["binary", "hex", "base", "conversion"],
    featured: false,
  },

  // File & Image Processing
  {
    id: "image-converter",
    name: "Image Converter & Editor",
    description: "Convert formats (PNG/JPEG/WebP/SVG/ICO), resize, and advanced cropping (multi-region rect/circle/polygon, magic wand, smart AI selection)",
    category: "files",
    icon: "🖼️",
    href: "/tools/conversion/image-converter",
    tags: ["image", "convert", "resize", "crop", "png", "jpeg", "webp", "svg", "ai", "smart-crop"],
    featured: true,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicon from text, emoji, or image",
    category: "files",
    icon: "✨",
    href: "/tools/files/favicon-generator",
    tags: ["favicon", "icon", "generate"],
    featured: false,
  },

  // Code & API Tools
  {
    id: "figma-to-code",
    name: "Figma to Next.js Code",
    description: "Extract Figma designs and convert to ready-to-use React/Tailwind components with asset URLs",
    category: "code",
    icon: "🎨",
    href: "/tools/code/figma-to-code",
    tags: ["figma", "react", "tailwind", "jsx", "design", "extract", "component"],
    featured: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and validate JWT tokens with detailed payload view",
    category: "code",
    icon: "🔑",
    href: "/tools/code/jwt-decoder",
    tags: ["jwt", "decode", "token", "auth"],
    featured: false,
  },
  {
    id: "regex-checker",
    name: "Regex Checker",
    description: "Test and validate regular expression patterns in real-time",
    category: "code",
    icon: "🔍",
    href: "/tools/code/regex-checker",
    tags: ["regex", "pattern", "test"],
    featured: false,
  },
  {
    id: "regex-generator",
    name: "Regex Generator",
    description: "Generate regex patterns from input/output examples",
    category: "code",
    icon: "⚡",
    href: "/tools/code/regex-generator",
    tags: ["regex", "pattern", "generate"],
    featured: false,
  },
  {
    id: "prettifier",
    name: "Prettifier",
    description: "Format, beautify, and validate files with syntax highlighting",
    category: "code",
    icon: "✨",
    href: "/tools/code/prettifier",
    tags: ["format", "pretty", "validate","json", "xml", "yaml", "css", "html", "js", "markdown"],
    featured: false,
  },
  {
    id: "fetch-curl",
    name: "Fetch ↔ cURL",
    description: "Convert between JavaScript fetch and cURL commands",
    category: "code",
    icon: "🔄",
    href: "/tools/code/fetch-curl",
    tags: ["fetch", "curl", "http", "api"],
    featured: false,
  },

  // Development Utilities
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text, URLs, or contact information",
    category: "dev-utils",
    icon: "📱",
    href: "/tools/dev-utils/qr-generator",
    tags: ["qr", "code", "generate"],
    featured: false,
  },
  {
    id: "url-shortener",
    name: "URL Shortener",
    description: "Shorten URLs using free public APIs with custom aliases",
    category: "dev-utils",
    icon: "🔗",
    href: "/tools/dev-utils/url-shortener",
    tags: ["url", "short", "link"],
    featured: false,
  },
  {
    id: "link-previewer",
    name: "Link Previewer",
    description: "Preview link metadata and Open Graph tags for SEO validation",
    category: "dev-utils",
    icon: "👁️",
    href: "/tools/dev-utils/link-previewer",
    tags: ["link", "preview", "seo", "metadata"],
    featured: false,
  },
  {
    id: "text-diff",
    name: "Text Difference Checker",
    description: "Compare two texts and highlight differences visually",
    category: "dev-utils",
    icon: "📋",
    href: "/tools/dev-utils/text-diff",
    tags: ["diff", "compare", "text"],
    featured: false,
  },
  {
    id: "postman",
    name: "Mini Postman",
    description: "Make HTTP requests with support for GET, POST, PUT, DELETE",
    category: "dev-utils",
    icon: "📮",
    href: "/tools/dev-utils/postman",
    tags: ["http", "api", "request", "postman"],
    featured: false,
  },

  // Generators & Config
  {
    id: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for different frameworks and languages",
    category: "generators",
    icon: "📦",
    href: "/tools/generators/gitignore",
    tags: ["gitignore", "git", "generate"],
    featured: false,
  },
  {
    id: "sitemap-generator",
    name: "Sitemap & robots.txt Generator",
    description: "Generate sitemap.xml and robots.txt for your website",
    category: "generators",
    icon: "🗺️",
    href: "/tools/generators/sitemap",
    tags: ["sitemap", "robots.txt", "seo"],
    featured: false,
  },
  {
    id: "git-commands",
    name: "Git Commands Helper",
    description: "Search and copy common git commands with explanations",
    category: "generators",
    icon: "🐙",
    href: "/tools/generators/git-commands",
    tags: ["git", "commands", "helper"],
    featured: false,
  },

  // Advanced Tools
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Live currency conversion with real-time exchange rates",
    category: "advanced",
    icon: "💱",
    href: "/tools/advanced/currency",
    tags: ["currency", "convert", "exchange", "live"],
    featured: false,
  },
  {
    id: "gee-image",
    name: "GEE Image Getter",
    description: "Google Earth Engine image retrieval with custom parameters",
    category: "advanced",
    icon: "🛰️",
    href: "/tools/advanced/gee-image",
    tags: ["google earth engine", "satellite", "image"],
    comingSoon: false,
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  conversion: "from-blue-500/10 to-blue-500/5 border-blue-200 dark:border-blue-800",
  files: "from-purple-500/10 to-purple-500/5 border-purple-200 dark:border-purple-800",
  code: "from-green-500/10 to-green-500/5 border-green-200 dark:border-green-800",
  "dev-utils": "from-amber-500/10 to-amber-500/5 border-amber-200 dark:border-amber-800",
  generators: "from-red-500/10 to-red-500/5 border-red-200 dark:border-red-800",
  advanced: "from-pink-500/10 to-pink-500/5 border-pink-200 dark:border-pink-800",
};

export const CATEGORY_BADGE_COLORS: Record<string, string> = {
  conversion: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100",
  files: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-100",
  code: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100",
  "dev-utils": "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-100",
  generators: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-100",
  advanced: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-100",
};
